export const projects = [
  {
    name: "Ambiance",
    description:
      "AI app that listens to your DnD story to play the right music.",
    url: "https://ambiance.florentklein.dev/",
    github: "https://github.com/floklein/ambiance",
    tags: [
      "Gemini",
      "Vite",
      "TanStack Router",
      "Tailwind",
      "Shadcn",
      "TanStack Query",
      "Bun",
      "Hono",
      "tRPC",
      "BetterAuth",
      "PostgreSQL",
      "Drizzle",
    ],
  },
  {
    name: "great minds",
    description: "Real-time party game to play with friends.",
    url: "https://greatminds.gg/",
    tags: [
      "Vite",
      "WebSocket",
      "Ant Design",
      "Colyseus",
      "Motion",
      "TanStack Query",
    ],
  },
  {
    name: "Artguessr",
    description: "Educative game about finding the date of an artwork.",
    github: "https://github.com/floklein/artguessr",
    url: "https://artguessr.florentklein.dev/",
    tags: ["Next.js", "Tailwind", "Shadcn", "Zod"],
  },
  {
    name: "kAI",
    description: "Multimodal AI client for Chrome-integrated Gemini Nano.",
    github: "https://github.com/floklein/kai",
    url: "https://kai.florentklein.dev/",
    tags: ["Vite", "Dexie", "TanStack Router", "Tailwind", "Shadcn"],
  },
  {
    name: "HALP!",
    description: "Social app around polls for iOS, Android and web.",
    github: "https://github.com/floklein/halp",
    url: "https://halp.florentklein.dev/",
    tags: ["React Native", "Expo", "PostgreSQL", "Drizzle", "BetterAuth"],
  },
  {
    name: "florentklein.dev",
    description: "This very portfolio, with its AI assistant.",
    github: "https://github.com/floklein/florentklein",
    url: "https://florentklein.dev/",
    tags: ["Astro", "OpenRouter", "DeepSeek", "Tailwind", "Shadcn"],
  },
  {
    name: "Mailectron",
    description: "Simple email desktop app, for macOS and Windows.",
    tags: ["Electron", "tRPC", "Supabase", "Turborepo", "Tailwind", "Shadcn"],
  },
];
