export const projects = [
  {
    name: "Ambiance",
    description:
      "App IA qui écoute votre scénario de jeu de rôle pour jouer la musique appropriée.",
    url: "https://ambiance.florentklein.dev/",
    github: "https://github.com/floklein/ambiance",
    tags: [
      "Vite",
      "TanStack Router",
      "TanStack Query",
      "Bun",
      "Hono",
      "tRPC",
      "BetterAuth",
      "Drizzle",
      "Gemini",
      "Tailwind",
      "Shadcn",
    ],
  },
  {
    name: "Terra TCG",
    description:
      "Jeu mobile de cartes à collectionner où vous capturez des animaux en les photographiant.",
    github: "https://github.com/floklein/terra",
    tags: [
      "Claude Code",
      "React Native",
      "Expo",
      "IA",
      "BetterAuth",
      "Drizzle",
      "PostgreSQL",
    ],
  },
  {
    name: "great minds",
    description:
      "Jeu en temps réel pour tester votre complicité avec vos amis sur des thèmes variés.",
    url: "https://greatminds.florentklein.dev/",
    github: "https://github.com/floklein/greatminds",
    tags: [
      "Vite",
      "WebSocket",
      "Ant Design",
      "Colyseus",
      "Motion",
      "TanStack Query",
      "Zustand",
      "Turborepo",
    ],
  },
  {
    name: "Le jeu du Dico",
    description:
      "Jeu multijoueur où vous piégez vos amis en inventant des définitions de mots difficiles.",
    github: "https://github.com/floklein/dico",
    url: "https://dico.florentklein.dev/",
    tags: [
      "Codex",
      "Next.js",
      "AI SDK",
      "GPT-5.2",
      "Tailwind",
      "Shadcn",
      "Vitest",
    ],
  },
  {
    name: "Artguessr",
    description: "Jeu éducatif consistant à deviner la date d'une œuvre d'art.",
    github: "https://github.com/floklein/artguessr",
    url: "https://artguessr.florentklein.dev/",
    tags: ["Next.js", "Tailwind", "Shadcn", "Zod"],
  },
  {
    name: "K3 Chat",
    description: "Chat IA multi-modal avec choix du modèle.",
    github: "https://github.com/floklein/k3chat",
    url: "https://cloneathon.t3.chat/",
    tags: [
      "Next.js",
      "Convex",
      "Gemini",
      "Claude",
      "GPT",
      "Tailwind",
      "Shadcn",
    ],
  },
  {
    name: "florentklein.dev",
    description: "Ce portfolio, avec son assistant IA.",
    github: "https://github.com/floklein/florentklein",
    url: "https://florentklein.dev/",
    tags: ["Next.js", "AI SDK", "GPT-5", "Tailwind", "Shadcn"],
  },
  {
    name: "kAI",
    description: "Chat IA multi-modal hors-ligne pour Chrome Gemini Nano.",
    github: "https://github.com/floklein/kai",
    tags: ["Vite", "Dexie", "TanStack Router", "Tailwind", "Shadcn"],
  },
  {
    name: "HALP!",
    description: "App sociale autour des sondages pour iOS, Android et le web.",
    github: "https://github.com/floklein/halp",
    tags: [
      "React Native",
      "Expo",
      "PostgreSQL",
      "Drizzle",
      "BetterAuth",
      "Tamagui",
    ],
  },
  {
    name: "Mailectron",
    description: "Client mail minimaliste pour macOS et Windows.",
    tags: ["Electron", "tRPC", "Supabase", "Turborepo", "Tailwind", "Shadcn"],
  },
];
